FROM amazoncorretto:17

# Set the working directory to /app
WORKDIR /app

# Copy the JAR file into the container at /app
COPY ./target/*.jar /app/app.jar

# Specify the command to run on container startup
CMD ["java", "-jar", "app.jar"]

# Dockerfile -> Dockerimage -> Docker Container